appVersion: 1.0.0
groupId: com.tmobile.security.taap
artifactId: lib-tmobile-poptoken-validator
mavenGoals: clean install -U

#JaCoCo ----------------------------------------------
percentClassCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
percentComplexityCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
percentInstructionCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
percentLineCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
percentMethodCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
percentBranchCoverageReq: '50' #if less than this value job will be marked as UNSTABLE
